### ISSUE TITLE
Integration of qtspeech with qt-pods

### ISSUE THREAD

**Issue by jacob3141** [yshurik/qtspeech#1]
See here for more info:
https://github.com/cybercatalyst/qt-pods

**Comment by yshurik** [comment]
what is it and why?

**Comment by jacob3141** [comment]
qt-pods is inspired by cocoapods, which is a "package manager" for iOS apps. I got in touch with it when working on my first iOS projects and was convinced of it very fast. It is simple, yet powerful.

qt-pods tries to even be a bit better: There is nothing like sources and packages, but the sources are the package. You have to follow a handful of simple rules so qt-pods knows how to clone, build and link your code automatically with a single click. It does not add anything to a qmake based project, just expects a few conventions.

The advantage is you can share your code very easy with other developers, other can try it out without hassle. Since your code is included as a simple git submodule, it is even updateable when you make changes. No complicated packaging for various distributions, no copy pasting source files around like you would usually do with smaller projects, and full version management.
