### ISSUE TITLE
How do i stop the voice read

### ISSUE THREAD

**Issue by prakashpun** [yshurik/qtspeech#5]
If i change the focus to different UI component that has QtSpeech enabled, then it clashes with previous text thats being read. How can i make sure only one text is read at a time.
Note that i cant use speech.say() function , because it freezes the UI.

Thanks

**Comment by yshurik** [comment]
There is possibility to use tell("hello", obj, SLOT(onFinish())), so you can simply set some boolean flag between tell() <--> onFinish() as indication to prevent other invokes of tell() routines.

**Comment by prakashpun** [comment]
Hi yshurik,

Thanks for the reply, what i meant to say is while the older text is being read, if I move the focus to new UI,  I want the older text speech to stop and start reading the new text.
Is that possible ? 
Dont know if this question is silly, beginner here.

Thanks

**Comment by yshurik** [comment]
Sapi (windows) implementation already has "stop" - https://github.com/yshurik/qtspeech/commit/3455128c76115af6c99a33aa9e679b37408ea671
But for mac version it may require some research to find appropriate api to use.
For linux(festival) as I remember there is no way to stop in middle at all.
